KB-8777: Very small changes on the client following number of usage
konverso-ai/open-chatbot-py-client pull request #1
Opened 2020-12-06 06:26 UTC by amedeepotier

I would also like to add Sasha... but I do not see him in the list of members. 
This is a very small change there..

2020-12-07 07:58 UTC, andreyjamer requested changes
Main questions are about code style. properties names are not obvious enough.
If we are building open source solution, then we should follow common style guides, like PEP8. For example class names should use the CapWords convention (https://www.python.org/dev/peps/pep-0008/#class-names). Current implementation does not use it.

2020-12-07 07:58 UTC, andreyjamer commented on openchatbotclient/response.py
> +        return self.jso.get('response', {}).get('query', '')
Why the property is named as `jso`? Is it for JSON? Or JSON Storable Object? I think it should be renamed into something simple and clear.

2020-12-07 07:58 UTC, andreyjamer commented on openchatbotclient/response.py
>          return self.cli
Why client is `cli`? CLI - is an acronym for Command Line Interface. I think this property should be renamed into `client`

2020-12-07 07:58 UTC, andreyjamer commented on openchatbotclient/response.py
> +        return self.jso.get('status', {}).get('code', '')
Result value is announced as `int`, but in get('code') default value is string. This is not good

2020-12-07 20:46 UTC, amedeepotier commented on openchatbotclient/response.py
> +        return self.jso.get('response', {}).get('query', '')
Understood your comment, but your note about invalid class name is related on this pull request !! Your note is about the original work itself. I am happy to rewrite the package to be compliant with the PIP recommendations... but I will not do this under this ticket, which is only about minor enhancements on the new properties). 

The new properties added in this PR are inline with the python recommendations.

2020-12-07 20:46 UTC, amedeepotier commented on openchatbotclient/response.py
>          return self.cli
Again, this is about previous code... not related to this PR. But yes, I do agree with you. Will make this change (but not on this PR, too late in the sprint to rewrite the package now)

2020-12-07 20:47 UTC, amedeepotier commented on openchatbotclient/response.py
> +        return self.jso.get('status', {}).get('code', '')
yes, good point. Will solve this shortly

2020-12-08 06:24 UTC, andreyjamer approved these changes
Approved

2020-12-10 04:27 UTC, merged

2020-12-10 04:27 UTC, amedeepotier commented
Merging to master