KB-8826: Align to the PIP8 naming conventions
konverso-ai/open-chatbot-py-client pull request #2
Opened 2020-12-15 04:31 UTC by amedeepotier

Objective of this PR is to align with the PIP8 standard. 

The only task done on this ticket is Class and Variable renaming.

2020-12-15 07:26 UTC, andreyjamer requested changes

2020-12-15 07:26 UTC, andreyjamer commented on openchatbotclient/client_group.py
> +        assert isinstance(cli, Client)
`cli` here means `client` or `command line interface`? If client, then may be better to name is client?

2020-12-15 07:26 UTC, andreyjamer commented on openchatbotclient/response.py
>          self.jso = data
Can `jso` be renamed into `json`?

2020-12-16 06:30 UTC, amedeepotier commented on openchatbotclient/client_group.py
> +        assert isinstance(cli, Client)
yes, it means "client". I renamed the variable accordingly

2020-12-16 06:30 UTC, amedeepotier commented on openchatbotclient/response.py
>          self.jso = data
yes, jso renamed to json

2020-12-16 07:02 UTC, andreyjamer requested changes

2020-12-16 07:02 UTC, andreyjamer commented on openchatbotclient/client_group.py
>          for cli in self:
Here we still have `cli`

2020-12-16 10:02 UTC, amedeepotier commented on openchatbotclient/client_group.py
>          for cli in self:
Corrected

2020-12-16 10:54 UTC, andreyjamer approved these changes

2020-12-16 16:05 UTC, merged